version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:10-alpine-ram
        environment:
          POSTGRES_PASSWORD: password

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn config set registry "https://registry.npmjs.org/"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - run:
          name: npm install
          command: npm i
      - run:
          name: test
          command: npm run test:unit && DIALECT=postgres npm run test:integration -- --exit
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release
